import {
  Network,
  BarChart3,
  Video,
  Code2,
  ShieldAlert,
  Zap,
  Server,
  Box,
} from "lucide-react";

export const site = {
  name: "Hossain Abedy",
  role: "Cybersecurity & Infrastructure Engineer",
  subtitle:
    "I build, secure, review, and automate enterprise systems across security operations, applications, and infrastructure. My work combines banking-scale operations, endpoint and network security, and practical engineering with automation and threat analysis.",
  email: "hossain.abedy@sbacbank.com",
  linkedin: "https://linkedin.com/in/hossainabedy",
  github: "https://github.com/HossainAbedy",
  cta: "Open to cybersecurity engineering, SOC operations, AppSec, network security, and automation roles.",
};

export const projects = [
  {
    title: "PC Inventory & Risk Analysis Platform",
    subtitle: "Asset Discovery, Endpoint Inspection, and Audit Reporting",
    desc: "A two-stage network discovery and deep endpoint inspection platform that builds a live inventory, scores risk, and generates audit-ready reports for branch and enterprise environments.",
    type: "Security Platform",
    risk: "High",
    coverage: "Enterprise Networks",
    status: "Operational",
    tags: ["Python", "PowerShell", "React", "MITRE ATT&CK"],
    accent: "cyan",
    icon: Network,
    images: [
      "/assets/images/Projects/PC-Inventory/PC-Inventory-1.png",
      "/assets/images/Projects/PC-Inventory/PC-Inventory-2.png",
      "/assets/images/Projects/PC-Inventory/PC-Inventory-3.png",
      "/assets/images/Projects/PC-Inventory/PC-Inventory-4.png",
      "/assets/images/Projects/PC-Inventory/PC-Inventory-5.png",
      "/assets/images/Projects/PC-Inventory/PC-Inventory-6.png",
      "/assets/images/Projects/PC-Inventory/PC-Inventory-7.png",
      "/assets/images/Projects/PC-Inventory/PC-Inventory-8.png",
      "/assets/images/Projects/PC-Inventory/PC-Inventory-9.png",
      "/assets/images/Projects/PC-Inventory/PC-Inventory-10.png",
      "/assets/images/Projects/PC-Inventory/PC-Inventory-11.png",
      "/assets/images/Projects/PC-Inventory/PC-Inventory-12.png",
      "/assets/images/Projects/PC-Inventory/PC-Inventory-13.png",
      "/assets/images/Projects/PC-Inventory/PC-Inventory-14.png",
    ],
    summary:
      "Built to map entire networks, inspect endpoints deeply, calculate posture-based risk, and export branch-specific or enterprise-wide reports with LAN diagrams.",
    highlights: [
      "Two scan modes: full network discovery and deep endpoint inspection",
      "Risk scoring based on patch status, OS version, antivirus posture, services, memory, hardware, and domain membership",
      "PDF export for branch-level and full-environment audit reporting",
      "LAN diagram support for visual review and documentation",
      "Frontend surfaces OS type, device posture, and branch-level mapping",
    ],
    stack: ["Python", "PowerShell", "React", "PDF Export", "MITRE Mapping"],
    impact: [
      "Improved asset visibility across distributed environments",
      "Standardized endpoint posture analysis for audit use",
      "Reduced manual inventory and reporting workload",
    ],
  },
  {
    title: "Attendance Sync Reliability Pipeline",
    subtitle: "Attendance Scheduler and Consistency Engine",
    desc: "A ZKTeco attendance collection pipeline with scheduled polling, duplicate prevention, and reliable synchronization into the HR application.",
    type: "Automation Pipeline",
    risk: "Medium",
    coverage: "Attendance Systems",
    status: "Operational",
    tags: ["Flask", "Python", "ThreadPool", "MySQL"],
    accent: "violet",
    icon: BarChart3,
    images: [
      "/assets/images/Projects/Att-System/Att-1.png",
      "/assets/images/Projects/Att-System/Att-2.png",
      "/assets/images/Projects/Att-System/Att-3.png",
      "/assets/images/Projects/Att-System/Att-4.png",
      "/assets/images/Projects/Att-System/Att-5.png",
      "/assets/images/Projects/Att-System/Att-6.png",
      "/assets/images/Projects/Att-System/Att-7.png",
      "/assets/images/Projects/Att-System/Att-8.png",
    ],
    summary:
      "Designed for reliable attendance collection, consistency control, and clean forwarding of validated records to the HR platform.",
    highlights: [
      "Scheduled polling from ZKTeco devices",
      "Thread pool based parallel scanning for speed and scale",
      "Atomic locks and duplicate checks for consistency",
      "Stored local copies before HR synchronization",
      "Frontend tracks uptime, reachability, and previous data states",
    ],
    stack: ["Python", "Flask", "MySQL", "ThreadPoolExecutor", "Atomic Locks"],
    impact: [
      "Reduced data inconsistency during sync",
      "Improved reliability of attendance collection",
      "Increased operational visibility across branches",
    ],
  },
  {
    title: "DVR Fleet Administration",
    subtitle: "Time Sync, Bulk Control, and Configuration Automation",
    desc: "A centralized Hikvision DVR management workflow for NTP enforcement, bulk password changes, and configuration automation.",
    type: "Device Management",
    risk: "Medium",
    coverage: "CCTV / DVR Fleet",
    status: "Operational",
    tags: ["PowerShell", "Hikvision API", "NTP", "Automation"],
    accent: "green",
    icon: Video,
    images: [
      "/assets/images/Projects/DVR-System/DVR-1.png",
      "/assets/images/Projects/DVR-System/DVR-2.png",
    ],
    summary:
      "Built to keep DVR fleets synchronized, centrally manageable, and easier to maintain through a control-plane style workflow.",
    highlights: [
      "Device time validation and NTP sync enforcement",
      "Bulk password changes through Hikvision APIs",
      "Backend processing for configuration management",
      "Uptime and health visibility from the frontend",
    ],
    stack: ["PowerShell", "Hikvision API", "NTP", "Backend Automation"],
    impact: [
      "Reduced manual DVR administration",
      "Improved device time consistency across the fleet",
      "Simplified bulk configuration workflows",
    ],
  },
  {
    title: "SafeOps Endpoint Health Review",
    subtitle: "PC Health and Status Checks",
    desc: "An operational utility for checking endpoint health, configuration state, and readiness across distributed branches.",
    type: "Health Monitoring",
    risk: "Low",
    coverage: "Branch Endpoints",
    status: "Operational",
    tags: ["Python", "Health Checks", "Operations", "Support"],
    accent: "blue",
    icon: Code2,
    images: [
      "/assets/images/Projects/SafeOps/Safe-1.png",
      "/assets/images/Projects/SafeOps/Safe-2.png",
      "/assets/images/Projects/SafeOps/Safe-3.png",
      "/assets/images/Projects/SafeOps/Safe-4.png",
      "/assets/images/Projects/SafeOps/Safe-5.png",
    ],
    summary:
      "Provides branch-wise scanning, health status display, remediation guidance, and SOP-aligned validation for endpoints.",
    highlights: [
      "Branch-wise scanning for distributed infrastructure visibility",
      "Real-time endpoint health status display",
      "Remediation guidance aligned with SOP",
      "Useful for audits, readiness checks, and support validation",
    ],
    stack: ["Python", "Monitoring", "Health Checks", "Operational Support"],
    impact: [
      "Improved endpoint readiness checks",
      "Helped operational support teams validate status quickly",
      "Added visibility for audit and remediation workflows",
    ],
  },
  {
    title: "Active Directory Migration & Automation",
    subtitle: "Domain Migration Framework",
    desc: "A large-scale Active Directory migration framework with automated post-deployment setup and branch-wide workstation handling.",
    type: "Migration",
    risk: "High",
    coverage: "125+ Branches",
    status: "Operational",
    tags: ["PowerShell", "AD", "Automation", "Enterprise"],
    accent: "indigo",
    icon: Server,
    images: [
      "/assets/images/Case Studies/AD/AD-1.png",
      "/assets/images/Case Studies/AD/AD-2.png",
      "/assets/images/Case Studies/AD/AD-3.png",
      "/assets/images/Case Studies/AD/AD-4.png",
      "/assets/images/Case Studies/AD/AD-5.png",
    ],
    summary:
      "Migrated workgroup systems into domain-managed environments and automated post-installation setup across 125+ branches.",
    highlights: [
      "Migrated endpoints from workgroup to domain across 125+ branches",
      "Reusable PowerShell framework for post-domain configuration",
      "Automated software installation, licensing, and policy enforcement",
      "Restored user desktops, documents, and shortcuts after migration",
    ],
    stack: ["PowerShell", "Active Directory", "GPO", "Deployment Automation"],
    impact: [
      "Standardized workstation configuration at scale",
      "Reduced migration downtime and manual setup effort",
      "Improved consistency across branches",
    ],
  },
  {
    title: "Legacy System Upgrade & Hardware Optimization",
    subtitle: "System Modernization Strategy",
    desc: "A remediation strategy for legacy Windows 7 environments using hardware upgrades where possible and Linux fallback options where upgrades were not feasible.",
    type: "Modernization Program",
    risk: "High",
    coverage: "Legacy Branch Systems",
    status: "Operational",
    tags: ["Windows", "Linux", "Hardware", "Operations"],
    accent: "orange",
    icon: Box,
    images: ["/assets/images/legacy-upgrade.png"],
    summary:
      "Improved security posture by identifying outdated systems, replacing unsupported hardware where possible, and using Linux alternatives where needed.",
    highlights: [
      "Identified and audited legacy Windows 7 systems across branches",
      "Performed hardware upgrades to support modern operating systems",
      "Deployed Linux alternatives for constrained devices",
      "Improved security by removing unsupported OS usage",
    ],
    stack: ["Windows 7", "Linux", "Hardware Refresh", "Asset Remediation"],
    impact: [
      "Reduced legacy OS exposure",
      "Extended usable hardware lifecycle",
      "Balanced security, cost, and operational continuity",
    ],
  },
];

export const caseStudies = [
  {
    title: "Wazuh SIEM Tuning & CIS Benchmark Hardening",
    tag: "DETECTION",
    accent: "cyan",
    metricLabel: "MEAN TIME TO DETECT",
    metric: "45m → 8m",
    images: [
      "/assets/images/Case Studies/Wazuh/Wazuh-1.png",
      "/assets/images/Case Studies/Wazuh/Wazuh-2.png",
      "/assets/images/Case Studies/Wazuh/Wazuh-3.png",
      "/assets/images/Case Studies/Wazuh/Wazuh-4.png",
      "/assets/images/Case Studies/Wazuh/Wazuh-5.png",
      "/assets/images/Case Studies/Wazuh/Wazuh-6.png",
      "/assets/images/Case Studies/Wazuh/Wazuh-7.png",
      "/assets/images/Case Studies/Wazuh/Wazuh-8.png",
    ],
    desc: "Improved detection quality through Wazuh rule tuning, alert optimization, and CIS benchmark hardening.",
    bullets: [
      "Analyzed high-volume alerts and tuned rules to reduce noise",
      "Optimized CIS benchmark findings for stronger endpoint hardening",
      "Improved dashboard visibility for IT hygiene, alerts, and agent status",
      "Strengthened SOC triage quality through cleaner signal and better prioritization",
    ],
  },
  {
    title: "FortiAnalyzer Monitoring & Log Correlation",
    tag: "MONITORING",
    accent: "violet",
    metricLabel: "LOG VISIBILITY",
    metric: "Centralized Analysis",
    images: [
      "/assets/images/Case Studies/FortiAnalyzer/FortiAnalyzer-1.png",
      "/assets/images/Case Studies/FortiAnalyzer/FortiAnalyzer-2.png",
      "/assets/images/Case Studies/FortiAnalyzer/FortiAnalyzer-3.png",
      "/assets/images/Case Studies/FortiAnalyzer/FortiAnalyzer-4.png",
      "/assets/images/Case Studies/FortiAnalyzer/FortiAnalyzer-5.png",
    ],
    desc: "Used FortiAnalyzer to review dashboards, threat activity, event monitors, and security logs for operational visibility.",
    bullets: [
      "Reviewed dashboards for centralized security visibility",
      "Investigated threat events and event monitor outputs",
      "Correlated logs to support triage and incident review",
      "Improved understanding of firewall-to-SOC event flow",
    ],
  },
  {
    title: "FortiGate Policy, Interface & Traffic Review",
    tag: "NETWORK",
    accent: "green",
    metricLabel: "PERIMETER CONTROL",
    metric: "Policy & Traffic Review",
    images: [
      "/assets/images/Case Studies/FortiGate/FortiGate-1.png",
      "/assets/images/Case Studies/FortiGate/FortiGate-2.png",
      "/assets/images/Case Studies/FortiGate/FortiGate-3.png",
      "/assets/images/Case Studies/FortiGate/FortiGate-4.png",
      "/assets/images/Case Studies/FortiGate/FortiGate-5.png",
    ],
    desc: "Reviewed FortiGate interfaces, address objects, security policies, and forward traffic to support secure branch operations.",
    bullets: [
      "Checked interfaces and perimeter connectivity status",
      "Reviewed address objects and security policy structure",
      "Analyzed forward traffic for operational insight",
      "Supported firewall hardening and branch network control",
    ],
  },
  {
    title: "PC Inventory Deep Scan & Audit Reporting",
    tag: "DETECTION",
    accent: "cyan",
    metricLabel: "RISK MAPPED TO MITRE",
    metric: "Endpoint Risk Scoring",
    images: [
      "/assets/images/Projects/PC-Inventory/PC-Inventory-1.png",
      "/assets/images/Projects/PC-Inventory/PC-Inventory-2.png",
      "/assets/images/Projects/PC-Inventory/PC-Inventory-3.png",
      "/assets/images/Projects/PC-Inventory/PC-Inventory-4.png",
      "/assets/images/Projects/PC-Inventory/PC-Inventory-5.png",
      "/assets/images/Projects/PC-Inventory/PC-Inventory-6.png",
      "/assets/images/Projects/PC-Inventory/PC-Inventory-7.png",
      "/assets/images/Projects/PC-Inventory/PC-Inventory-8.png",
      "/assets/images/Projects/PC-Inventory/PC-Inventory-9.png",
      "/assets/images/Projects/PC-Inventory/PC-Inventory-10.png",
      "/assets/images/Projects/PC-Inventory/PC-Inventory-11.png",
      "/assets/images/Projects/PC-Inventory/PC-Inventory-12.png",
      "/assets/images/Projects/PC-Inventory/PC-Inventory-13.png",
      "/assets/images/Projects/PC-Inventory/PC-Inventory-14.png",
    ],
    desc: "Built a two-stage inventory platform with network discovery, deep endpoint inspection, and audit-ready reporting.",
    bullets: [
      "Full network scan plus deep scan for detailed endpoint intelligence",
      "Risk calculated from patching, OS version, AV, services, RAM, hardware, and domain state",
      "Generated branch-specific and enterprise-wide audit outputs with LAN diagrams",
      "Mapped findings to MITRE techniques for structured remediation",
    ],
  },
  {
    title: "Attendance Sync Reliability Pipeline",
    tag: "AUTOMATION",
    accent: "violet",
    metricLabel: "CONSISTENCY CONTROL",
    metric: "Thread-Safe Sync",
    image: "/assets/images/attendance-sync.png",
    desc: "Automated ZKTeco attendance collection with duplicate prevention and reliable HR system synchronization.",
    bullets: [
      "Thread pool based device polling for speed and scale",
      "Atomic locking and duplicate checks for data consistency",
      "Frontend monitoring for uptime, reachability, and historical data validation",
      "Synchronized clean data into the HR app with duplication safeguards",
    ],
  },
  {
    title: "DVR Fleet Administration & Monitoring",
    tag: "ENGINEERING",
    accent: "green",
    metricLabel: "DEVICE CONTROL",
    metric: "Bulk Managed",
    image: "/assets/images/dvr-fleet.png",
    desc: "Centralized Hikvision DVR management platform with NTP enforcement, uptime monitoring, and configuration automation.",
    bullets: [
      "Time drift detection and automated NTP synchronization",
      "Bulk password changes using Hikvision APIs",
      "Frontend-driven configuration and monitoring pipeline",
      "Managed device health and status from the backend",
    ],
  },
  {
    title: "SafeOps Endpoint Health Review",
    tag: "OPERATIONS",
    accent: "blue",
    metricLabel: "HEALTH STATUS",
    metric: "Real-Time Visibility",
    image: "/assets/images/safeops-health.png",
    desc: "Internal system for endpoint health monitoring, audit preparation, operational readiness checks, and critical update validation.",
    bullets: [
      "Branch-wise scanning for distributed infrastructure visibility",
      "Real-time health status display across endpoints",
      "Remediation guidance aligned with SOP and audit workflows",
      "Useful for readiness checks and support validation",
    ],
  },
  {
    title: "Active Directory Migration & Automation",
    tag: "INFRASTRUCTURE",
    accent: "indigo",
    metricLabel: "DEPLOYMENT SCALE",
    metric: "125+ Branches",
    images: [
      "/assets/images/Case Studies/AD/AD-1.png",
      "/assets/images/Case Studies/AD/AD-2.png",
      "/assets/images/Case Studies/AD/AD-3.png",
      "/assets/images/Case Studies/AD/AD-4.png",
      "/assets/images/Case Studies/AD/AD-5.png",
    ],
    desc: "Executed large-scale Active Directory migration with automated post-deployment configuration across distributed banking infrastructure.",
    bullets: [
      "Migrated endpoints from workgroup to domain across 125+ branches",
      "Developed reusable PowerShell automation for post-domain configuration",
      "Automated software installation, licensing, and policy enforcement",
      "Restored user environments and system configurations seamlessly",
      "Standardized domain setup aligned with organizational policies",
    ],
  },
  {
    title: "Legacy System Upgrade & Hardware Optimization",
    tag: "OPERATIONS",
    accent: "orange",
    metricLabel: "SYSTEM MODERNIZATION",
    metric: "Win7 → Secure OS",
    image: "/assets/images/legacy-upgrade-case.png",
    desc: "Led remediation of legacy systems by upgrading unsupported Windows environments and optimizing hardware usage.",
    bullets: [
      "Identified and audited legacy Windows 7 systems across branches",
      "Performed hardware upgrades to support modern operating systems",
      "Deployed Linux alternatives for low-resource systems where upgrades were not feasible",
      "Improved security posture by eliminating unsupported OS usage",
      "Extended system lifecycle while maintaining operational continuity",
    ],
  },
  {
    title: "Security & Infrastructure Automation",
    tag: "ENGINEERING",
    accent: "indigo",
    metricLabel: "DEPLOYMENT EFFICIENCY",
    metric: "Hours → Minutes",
    images: [
      "/assets/images/Case Studies/Automation/Automation-1.png",
      "/assets/images/Case Studies/Automation/Automation-2.png",
      "/assets/images/Case Studies/Automation/Automation-3.png",
      "/assets/images/Case Studies/Automation/Automation-4.png",
    ],
    desc: "Built reusable automation frameworks for infrastructure provisioning, endpoint standardization, and operational support.",
    bullets: [
      "Automated post-domain configuration and user environment restoration",
      "Standardized software deployment, licensing, and system baselines across 125+ branches",
      "Developed reusable scripts for monitoring, reporting, and endpoint validation",
      "Reduced deployment time and eliminated manual configuration inconsistencies",
    ],
  },
  {
    title: "SOC Automation & Incident Response Acceleration",
    tag: "DETECTION",
    accent: "green",
    metricLabel: "RESPONSE TIME",
    metric: "−74%",
    image: "/assets/images/security-automation.png",
    desc: "Designed automation workflows to accelerate security triage, alert enrichment, and incident response across SOC operations.",
    bullets: [
      "Built response playbooks for phishing, malware, and brute-force scenarios",
      "Automated alert enrichment with contextual data for faster triage",
      "Streamlined correlation between logs, alerts, and endpoint signals",
      "Reduced analyst fatigue and improved consistency in incident handling",
    ],
  },
  {
    title: "Banking Branch Security Hardening",
    tag: "COMPLIANCE",
    accent: "amber",
    metricLabel: "AUDIT SUCCESS",
    metric: "100%",
    image: "/assets/images/branch-hardening.png",
    desc: "Standardized security baselines and improved compliance across distributed banking branches while maintaining continuity.",
    bullets: [
      "Group Policy-based baseline enforcement",
      "Automated audit reporting and remediation tracking",
      "Aligned with regulatory and operational requirements",
    ],
  },
  {
    title: "AppSec Code Review & Remediation",
    tag: "APPSEC",
    accent: "violet",
    metricLabel: "CRITICAL FIXES",
    metric: "Dozens Resolved",
    image: "/assets/images/appsec-review.png",
    desc: "Identified and remediated critical vulnerabilities through manual and AI-assisted code review.",
    bullets: [
      "OWASP Top 10 and logic flaw identification",
      "Manual and AI-assisted analysis techniques",
      "Improved secure development practices",
    ],
  },
  {
    title: "Network Security Audit",
    tag: "NETWORK",
    accent: "cyan",
    metricLabel: "POLICY ISSUES",
    metric: "Hundreds Identified",
    image: "/assets/images/network-audit.png",
    desc: "Performed firewall and segmentation audits across enterprise environments and hardened configurations based on findings.",
    bullets: [
      "Firewall rule review and optimization",
      "Segmentation strategy improvements",
      "IDS/IPS tuning for real-world traffic",
    ],
  },
  {
    title: "Vulnerability Assessment",
    tag: "PENTEST",
    accent: "red",
    metricLabel: "RISK REDUCTION",
    metric: "Critical → Controlled",
    image: "/assets/images/vapt.png",
    desc: "Conducted vulnerability assessments and penetration testing with structured remediation planning and validation.",
    bullets: [
      "Black-box and white-box testing approaches",
      "Exploit validation and risk scoring",
      "Remediation tracking and verification",
    ],
  },
];

export const capabilities = [
  {
    title: "Security Operations",
    icon: ShieldAlert,
    color: "cyan",
    bullets: [
      "SOC monitoring and incident response",
      "Wazuh SIEM and FortiAnalyzer analysis",
      "Threat intelligence integration",
      "Operational alert review and triage",
    ],
    tags: ["Wazuh", "FortiAnalyzer", "MITRE ATT&CK"],
  },
  {
    title: "Security Automation",
    icon: Zap,
    color: "green",
    bullets: [
      "SOAR-style workflow design and scripting",
      "Python, Bash, and PowerShell automation",
      "Alert enrichment and auto-response",
      "Operational task reduction",
    ],
    tags: ["Python", "PowerShell", "Bash"],
  },
  {
    title: "AppSec & Code Review",
    icon: Code2,
    color: "red",
    bullets: [
      "Source code security review",
      "OWASP Top 10 analysis",
      "Secure SDLC integration",
      "Developer security guidance",
    ],
    tags: ["Semgrep", "Burp Suite", "SAST/DAST"],
  },
  {
    title: "Network Security",
    icon: Network,
    color: "amber",
    bullets: [
      "Firewall architecture and policy",
      "Network segmentation design",
      "IDS/IPS tuning and deployment",
      "VPN and branch hardening",
    ],
    tags: ["FortiGate", "Suricata", "Zero Trust"],
  },
  {
    title: "System Administration",
    icon: Server,
    color: "blue",
    bullets: [
      "Windows Server and Active Directory",
      "Group Policy hardening",
      "Antivirus server administration",
      "Linux system management",
    ],
    tags: ["AD/GPO", "Kaspersky", "Nikash"],
  },
  {
    title: "Full-Stack Development",
    icon: Box,
    color: "violet",
    bullets: [
      "Full-stack web applications",
      "REST APIs and backend services",
      "Database design and optimization",
      "Security-first architecture",
    ],
    tags: ["React", "Vue", "Laravel", "Flask", "SQL"],
  },
];

export const skills = [
  "VMware & Lab Environments",
  "VAPT & Pen Testing",
  "Office IT Hardware Setup",
  "Endpoint Management",
  "Docker & Kubernetes",
  "Incident Forensics & IR",
  "Compliance Frameworks",
  "Data Privacy & GDPR",
];

export const philosophy = [
  [
    "Trace Input to Sink",
    "Follow every data path from entry point to execution. Understand the full attack surface.",
  ],
  [
    "Validate Exploitability",
    "A finding is not real until impact is proven. Theory and reality are different.",
  ],
  [
    "Separate Signal from Noise",
    "Eliminate false positives aggressively. Trust in alerts drives action.",
  ],
  [
    "Think in Attack Paths",
    "Chain findings together. Understand what an adversary would do next.",
  ],
];

export const experience = [
  {
    logo: "/assets/images/Logos/SBAC.png",
    title: "Assistant Officer",
    company: "SBAC Bank PLC",
    type: "Full-time",
    period: "Jul 2024 – Present",
    location: "Dhaka, Bangladesh · On-site",
    accent: "cyan",
    bullets: [
      "Supported IT security and operations across 120 branches and approximately 1,500 endpoints",
      "Administered Wazuh/Elastic SIEM and FortiAnalyzer for log review, threat detection, and visibility",
      "Configured and maintained FortiGate 400E/1000E firewalls, VPNs, policies, segmentation, and SSL inspection",
      "Managed Kaspersky Endpoint Security server and enforced patch and antivirus compliance",
      "Oversaw Active Directory user lifecycle, group transfers, and Group Policy management",
      "Built automation scripts in PowerShell and Python to reduce onboarding and audit effort",
      "Supported branch-level IT including routers, switches, VLANs, VPNs, CCTV, and attendance systems",
      "Conducted IT audits per Bangladesh Bank guidelines and migrated PCs to the bank domain",
      "Developed internal dashboards and inventory apps using Flask and React",
    ],
    stack: ["Wazuh", "FortiAnalyzer", "FortiGate", "Kaspersky", "Active Directory"],
  },
  {
    logo: "/assets/images/Logos/SBAC.png",
    title: "Trainee Assistant Officer",
    company: "SBAC Bank PLC",
    type: "Full-time",
    period: "Jul 2023 – Jul 2024",
    location: "Dhaka, Bangladesh · On-site",
    accent: "blue",
    bullets: [
      "Supported security operations and vulnerability-related tasks",
      "Assisted with branch IT support and security administration workflows",
      "Built operational familiarity with banking infrastructure and compliance expectations",
    ],
    stack: ["Security Operations", "Vulnerability Support", "Branch IT"],
  },
  {
    logo: "/assets/images/Logos/SIGMIND.png",
    title: "Network Engineer",
    company: "SIGMIND.ai",
    type: "Contract",
    period: "Jan 2023 – Jul 2023",
    location: "Dhaka, Bangladesh · Hybrid",
    accent: "green",
    bullets: [
      "Configured LAN/WAN, ACLs, and routing for secure AI research infrastructure",
      "Conducted vulnerability assessments and applied mitigations",
      "Supported secure network operations in a hybrid environment",
    ],
    stack: ["LAN/WAN", "ACLs", "Routing", "Vulnerability Assessment"],
  },
  {
    logo: "/assets/images/Logos/CODECAMP.png",
    title: "Coding Teacher",
    company: "Code Camp",
    type: "Contract",
    period: "Oct 2022 – Dec 2022",
    location: "Melbourne, Victoria, Australia · On-site",
    accent: "amber",
    bullets: [
      "Ran summer programming camps teaching coding fundamentals to school students",
      "Delivered lessons in basic programming, problem-solving, and game development concepts",
      "Strengthened communication, leadership, and presentation skills through mentoring",
    ],
    stack: ["Teaching", "Communication", "Problem Solving"],
  },
  {
    logo: "/assets/images/Logos/TELSTRA.png",
    title: "Customer Service Representative",
    company: "Telstra",
    type: "Full-time",
    period: "Jul 2022 – Sep 2022",
    location: "Melbourne, Victoria, Australia",
    accent: "violet",
    bullets: [
      "Worked in the Credit Management Team and Financial Assistance and Support Team",
      "Assisted customers facing financial hardship with bill support and account changes",
      "Handled discounts, payment extensions, account holds, and service restrictions",
      "Used Telstra systems to update account details and troubleshoot related issues",
    ],
    stack: ["Salesforce", "Customer Support", "Case Handling"],
  },
  {
    logo: "/assets/images/Logos/SAFARA.png",
    title: "Junior Programmer / Software Developer",
    company: "Safara IT (Concern of Edison Foundation)",
    type: "Full-time",
    period: "Sep 2019 – Nov 2019",
    location: "Badda, Bangladesh",
    accent: "indigo",
    bullets: [
      "Started as a Laravel backend developer and later advanced into Vue.js frontend development",
      "Developed and maintained an ERP solution for Auko Tex Garments covering production, HR, accounts, and supply chain",
      "Acted as primary spokesperson for the software during client meetings, demos, and training sessions",
      "Visited client sites to provide end-user training and gathered requirements for new modules",
      "Enhanced ERP modules across both frontend and backend for scalability and usability",
    ],
    stack: ["Laravel", "Vue.js", "ERP", "Client Training"],
  },
  {
    logo: "/assets/images/Logos/SAFARA.png",
    title: "Software Engineer Intern",
    company: "Safara IT (Concern of Edison Foundation)",
    type: "Internship",
    period: "Feb 2019 – Aug 2019",
    location: "Baridhara, Bangladesh",
    accent: "slate",
    bullets: [
      "Supported full-scale web development tasks with senior guidance",
      "Contributed to feature development, debugging, and application improvements",
      "Built practical experience in production-style web workflows",
    ],
    stack: ["Web Development", "Debugging", "Feature Work"],
  },
];

export const education = [
  {
    logo: "/assets/images/Logos/LTU.png",
    school: "La Trobe University",
    degree: "Master's Degree, Cybersecurity",
    period: "2020 – 2022",
    location: "Melbourne, Victoria, Australia",
    accent: "violet",
    bullets: [
      "Advanced coursework in cryptography, digital forensics, network security, threat modelling, and privacy",
      "Completed research and practical work aligned with modern security operations",
    ],
  },
  {
    logo: "/assets/images/Logos/EWU.png",
    school: "East West University",
    degree: "Bachelor of Science, Computer Science and Engineering",
    period: "2014 – 2018",
    location: "Dhaka, Bangladesh",
    accent: "cyan",
    bullets: [
      "Built strong foundations in programming, software engineering, and computer systems",
      "Prepared the technical base for later work in cybersecurity and full-stack development",
    ],
  },
];

export const certifications = [
  {
    logo: "/assets/images/Logos/COMPTIA.png",
    name: "CompTIA Network+ (N10-007)",
    issuer: "CompTIA",
    issued: "Nov 2020",
    expires: "Nov 2023",
    credentialId: "",
    accent: "cyan",
    skills: [
      "Networking Fundamentals",
      "Routing and Switching",
      "Network Security",
      "Troubleshooting",
    ],
    certificateImage: "/assets/images/Logos/NET.png",
    certificateLink: "",
  },
  {
    logo: "/assets/images/Logos/COMPTIA.png",
    name: "CompTIA Security+ (SY0-501)",
    issuer: "CompTIA",
    issued: "Feb 2021",
    expires: "Feb 2024",
    credentialId: "",
    accent: "green",
    skills: [
      "Threat Detection",
      "Risk Management",
      "Cryptography",
      "Security Operations",
    ],
    certificateImage: "/assets/images/Logos/SEC.png",
    certificateLink: "",
  },
  {
    logo: "/assets/images/Logos/LTU.png",
    name: "Cyber Technologies",
    issuer: "La Trobe University (CSE)",
    issued: "Oct 2022",
    expires: "Lifetime",
    credentialId: "",
    accent: "blue",
    skills: [
      "Cybersecurity Fundamentals",
      "Secure Systems",
      "Threat Analysis",
    ],
    certificateImage: "/assets/images/Logos/LTU.png",
    certificateLink: "",
  },
  {
    logo: "/assets/images/Logos/EC.png",
    name: "Master Wireshark 3 in 5 Days",
    issuer: "EC-Council",
    issued: "Aug 2023",
    expires: "Lifetime",
    credentialId: "239074",
    accent: "indigo",
    skills: [
      "Packet Analysis",
      "Network Troubleshooting",
      "Traffic Inspection",
    ],
    certificateImage: "/assets/images/Logos/EC.png",
    certificateLink: "",
  },
];

export const publications = [
  {
    logo: "/assets/images/Logos/IEEE.png",
    title:
      "Leukemia Prediction from Microscopic Images of Human Blood Cell Using HOG Feature Descriptor and Logistic Regression",
    venue:
      "2018 16th International Conference on ICT and Knowledge Engineering (ICT&KE)",
    publisher: "IEEE",
    issued: "Jan 17, 2019",
    accent: "red",
    doi: "10.1109/ICTKE.2018.8612303",
    link: "https://doi.org/10.1109/ICTKE.2018.8612303",
  },
];